### ISSUE TITLE
Add labels for links.

### ISSUE THREAD

**Issue by tokarchyn** [tokarchyn/react-easy-diagram#2]
In addition to just add simple labels as a text, consider also how they can be customized, if it would be possible to add multiple labels and so on.

**Comment by usamedin** [comment]
@tokarchyn when do you think this will be available?

**Comment by tokarchyn** [comment]
@usamedin Hi, probably after the weekend. How would you like to use it?

**Comment by usamedin** [comment]
I would add numbers on (top middle) of the line to indicate moving parts in the diagram.

**Comment by tokarchyn** [comment]
@usamedin Hi, after a short research of existing libraries for doing diagrams I decided to close this repo. Please, read the Readme page. Nevertheless, thank you for your interest in this package🙂.

**Comment by medin-n** [comment]
Damn, that was close i was planning to start working on this from next week.
Thanks for the notice
