### ISSUE TITLE
Add an update to render le link with html node (contentEditable)

### ISSUE THREAD

**Issue by code-dev-pro** [tokarchyn/react-easy-diagram#4]
<img width="585" alt="Capture d’écran 2021-08-22 à 15 17 58" src="https://user-images.githubusercontent.com/254780/130356778-d72f0ebc-d668-47f8-8d4f-77cad382db36.png">
<img width="572" alt="Capture d’écran 2021-08-22 à 15 18 08" src="https://user-images.githubusercontent.com/254780/130356779-0e74e11b-9056-42e7-b8aa-ce1a2c65215b.png">
Is it possible to update the render line when content change size ?

**Comment by tokarchyn** [comment]
Hi! Yes, it's possible. There are two ways to do it, rather by storing your node state in node's extra field, or by calling node.recalculatePortsSizeAndPosition() whenever you think size might has changed. There is also [example ](https://tokarchyn.github.io/react-easy-diagram/examples/updatePortsPosition) that demonstrates this.

**Comment by code-dev-pro** [comment]
Thanks. It’s a great tool !!!
