### ISSUE TITLE
Set the initstate with extra props

### ISSUE THREAD

**Issue by code-dev-pro** [tokarchyn/react-easy-diagram#7]
Hi,
Is it possible to init the initstate with extra saved ? The node uses id or label for the content but not extra. 
I used it for saving image, html content…
![5A621FD0-D430-40A0-BD67-B3547087D095](https://user-images.githubusercontent.com/254780/132160430-9e8719e8-d3aa-4cd5-b7b1-c32d1f1f2271.jpeg)

Thanks.

**Comment by code-dev-pro** [comment]
I found a solution by the proxy. Il will be great to have like setExtra a getExtra method.

**Comment by tokarchyn** [comment]
Hi! 
Do I understand correctly that you want to save your own properties the same way like "id", "label" and "extra"? For example, you would like to write something like this:
```
<Diagram
    initState={{
      nodes: [
        {
          id: 'external',
          position: [0, 0],
          extra: { html = 'somehtml', image: 'img' },
          yourCustomProp: 12345,
          type: 'external',
        }]
     }} />
```
and then, be able to set and get those properties with methods like "node.setYourCustomProp()" and "node.getYourCustomProp()". 
If it is not what you expect from library, could you please provide some example? Thank you🙂

**Comment by code-dev-pro** [comment]
Thanks for the answer
