### ISSUE TITLE
Add arrow in the svg line

### ISSUE THREAD

**Issue by code-dev-pro** [tokarchyn/react-easy-diagram#8]
Is it possible to add this feature in the drawing by adding marker ?
<img width="973" alt="Capture d’écran 2021-09-07 à 08 07 08" src="https://user-images.githubusercontent.com/254780/132292763-1cb7588d-bcd1-4293-ad99-f68851934da9.png">
Thanks.

**Comment by tokarchyn** [comment]
Right now it can be done only by creating your own Link component and passing it to links settings. But I will try to make it more simple to replace link's endings and add default arrow component. I think by the end of the week it will be done.

**Comment by code-dev-pro** [comment]
Great ! Marker can be useful like this : http://tutorials.jenkov.com/svg/marker-element.html

**Comment by tokarchyn** [comment]
Hi @code-dev-pro,
I have added support for markers, you can check example [here](https://tokarchyn.github.io/react-easy-diagram/examples/linkMarkers). I whould be glad to hear your feedback 🙂

**Comment by code-dev-pro** [comment]
Hi ! It’s a great feature ! Thanks !
