### ISSUE TITLE
Multiple select to remove or clone

### ISSUE THREAD

**Issue by lokhmakov** [tokarchyn/react-easy-diagram#9]
I want to implement multiple selection. Any recommendations to do this better?

**Comment by tokarchyn** [comment]
Hello @lokhmakov! 
Could you please write more details how do you want to implement this? Because right now it is possible to multiple select nodes and links using ctrl + left mouse button combination, or just by tap and hold (the primary reason for this method is to support touch devices but it also works with mouse). Remove and clone commands already support multiple selection.

**Comment by lokhmakov** [comment]
@tokarchyn ctrl + left mouse show context menu on Mac.

**Comment by lokhmakov** [comment]
And this method is ok, except ctrl key. I will try to look on it, to find way to use it on touch screens and desktop (Mac).

**Comment by tokarchyn** [comment]
Right now I'm trying to create Mac instance on AWS to fix this bug you wrote about.
When it comes to touchscreen, I tested it on IPad, Iphone, Android and Windows laptop, did you run into some bug regarding it?

**Comment by lokhmakov** [comment]
I cannot multi select on iPad.

After double tap u can increase viewport and u cannot goes back.

2 minutes of testing! :)

**Comment by lokhmakov** [comment]
Idea: Double click (tap) to start multiselect area.

**Comment by tokarchyn** [comment]
Ouch, it's an annoying bug, I will fix it in an hour.
"Double click (tap) to start multiselect area." - I like this idea, thank you!  Do you feel right now that this is important feature for you to be able to select using "area"?

**Comment by lokhmakov** [comment]
Nope, I think one solution will be enough for now (shift or other). Area to the future releases.

**Comment by tokarchyn** [comment]
So, problem with double touch on IOS is resolved. 

I will change key to press for multiselection to "shift" as it works well for all OS. Maybe library will enable to configure this key for each OS.

@lokhmakov You wrote that "I cannot multi select on iPad.", can you please provide information if you use tap and hold method or you try double tap to multiselect(it's not supported)? I tried it on my IPad on Safari and Chrome and it works..

**Comment by lokhmakov** [comment]
@tokarchyn It was not clear to me how this should be done. It all worked now.

**Comment by lokhmakov** [comment]
@tokarchyn This is how it is done in Miro:

<img width="567" alt="Screenshot 2021-09-29 at 23 04 14" src="https://user-images.githubusercontent.com/94939/135340512-1d556202-c4e7-420c-aeb2-a4376b78d108.png">

**Comment by tokarchyn** [comment]
Thank you @lokhmakov for the ideas!

Btw the default key to multiselect is now "shift", but it can be configurated, see [documentation](https://tokarchyn.github.io/react-easy-diagram/docs/userInteraction).

@lokhmakov if you think this problem is resolved feel free to close the issue.
